version: "3"
services:
  nginx:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - ${FRONTEND_PORT:-3000}:80
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://localhost:5000}:5000
    volumes:
    - ./app:/app