version: "3"
services:
  nginx:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - ${FRONTEND_PORT:-3001}:80
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL:-http://192.168.200.12:5001}
    volumes:
      - ./app:/app
